"""로컬 D1 시드 생성기 — 팀 D1(읽기 전용)에서 culture 7종 샘플을 추출해 seed.sql 을 쓴다.

사용법 (레포 루트 sample/ 에서, .env 의 CLOUDFLARE_API_TOKEN 필요):
    python serving-gateway/fixtures/build_fixtures.py

산출물 seed.sql 은 커밋한다 — 팀원은 토큰 없이 `npm run seed` 만으로 로컬 D1 이 선다.
_catalog 는 계약 v1.1(15컬럼, ASAC-DBT#346) 기준 픽스처 — 라이브 8컬럼 스키마와 다르며
그게 의도다(ASAC-DAG#521 이후의 목표 상태를 로컬에서 먼저 산다).
"""
from __future__ import annotations

import json
import os
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ACCOUNT = "0d39ddce1c07c97df66843ede19f56c4"
DATABASE = "9db0e851-558e-489f-9e76-f131d25aa267"
API = f"https://api.cloudflare.com/client/v4/accounts/{ACCOUNT}/d1/database/{DATABASE}/query"
SAMPLE_ROWS = 50

# (table, product_id, product_question, time_axis) — ASAC-DBT#346 meta.serving 계약값
PRODUCTS = [
    ("gold_culture_activity_by_dong", "culture_activity_by_dong", "어느 행정동에서 언제 문화 활동이 얼마나 열리나?", "event_date"),
    ("gold_culture_calendar_density", "culture_calendar_density", "구별로 어느 날짜에 행사가 몰리나(밀집도)?", "event_date"),
    ("gold_culture_event_schedule", "culture_event_schedule", "이번 주말·특정 기간 서울에서 무슨 문화행사가 열리나?", "event_start_date"),
    ("gold_culture_event_crowd", "culture_event_crowd", "무슨 요일 몇 시에 행사 주변이 붐비나?", None),
    ("gold_culture_boxoffice_daily", "culture_boxoffice_daily", "지금 서울에서 예매 상위 공연은 무엇인가?", "snapshot_date"),
    ("gold_culture_dine_around", "culture_dine_around", "행사 많은 동네 주변 외식 상권은 어디인가?", None),
    ("gold_culture_booking_curve", "culture_booking_curve", "공연 예매 인기가 개막까지 어떤 궤적으로 차오르나?", None),
]

CATALOG_DDL = (
    "CREATE TABLE IF NOT EXISTS _catalog (name TEXT PRIMARY KEY, product_id TEXT, "
    "external INTEGER, description TEXT, product_question TEXT, tests TEXT, time_axis TEXT, "
    "columns TEXT, row_count INTEGER, serving_status TEXT, publication_id TEXT, "
    "source_run_id TEXT, published_bytes INTEGER, freshness TEXT, exported_at TEXT);"
)


def d1(sql: str) -> list[dict]:
    token = os.environ.get("CLOUDFLARE_API_TOKEN", "")
    if not token:
        raise SystemExit("CLOUDFLARE_API_TOKEN 미설정 — sample/.env 값을 환경변수로 넘겨 실행")
    req = urllib.request.Request(
        API,
        data=json.dumps({"sql": sql}).encode(),
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req) as resp:
        body = json.load(resp)
    if not body.get("success"):
        raise SystemExit(f"D1 오류: {body.get('errors')}")
    return body["result"][0]["results"]


def lit(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    out: list[str] = ["-- generated by build_fixtures.py — 팀 D1 샘플 (테이블당 최대 %d행)" % SAMPLE_ROWS]
    out.append(CATALOG_DDL)
    now = datetime.now(timezone.utc).isoformat()

    for table, product_id, question, time_axis in PRODUCTS:
        info = d1(f"PRAGMA table_info({table})")
        cols = [(c["name"], c["type"] or "TEXT") for c in info]
        col_defs = ", ".join(f'"{n}" {t}' for n, t in cols)
        out.append(f'DROP TABLE IF EXISTS "{table}";')
        out.append(f'CREATE TABLE "{table}" ({col_defs});')

        total = d1(f'SELECT COUNT(*) AS n FROM "{table}"')[0]["n"]
        rows = d1(f'SELECT * FROM "{table}" LIMIT {SAMPLE_ROWS}')
        names = ", ".join(f'"{n}"' for n, _ in cols)
        for r in rows:
            values = ", ".join(lit(r.get(n)) for n, _ in cols)
            out.append(f'INSERT INTO "{table}" ({names}) VALUES ({values});')

        columns_json = json.dumps([{"name": n, "type": t} for n, t in cols], ensure_ascii=False)
        out.append(
            "INSERT OR REPLACE INTO _catalog (name, product_id, external, description, product_question, "
            "tests, time_axis, columns, row_count, serving_status, publication_id, source_run_id, "
            "published_bytes, freshness, exported_at) VALUES ("
            + ", ".join([
                lit(table), lit(product_id), "1", lit(f"culture 외부 gold — {product_id}"), lit(question),
                "'[]'", lit(time_axis), lit(columns_json), str(total), "'published'",
                "'local-fixture'", "'local-fixture'", "0", "NULL", lit(now),
            ])
            + ");"
        )
        print(f"{table}: sample={len(rows)} full={total}")

    seed = Path(__file__).with_name("seed.sql")
    seed.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {seed} ({seed.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
